"""
Enforces safety and structural correctness for AI-generated
file organization plans before they are executed by the system.

Acts as a deterministic guardrail between the LLM-generated plan
and selectively exposed filesystem operations.
"""

from typing import List, Dict
import os

ALLOWED_ACTIONS = {"move_item", "create_folder"}
MAX_ACTIONS = 200


def validate_plan(plan: List[Dict], root_dir: str) -> List[Dict]:
    """
    Validates an entire execution plan generated by the LLM.

    This function ensures that all actions in the plan are:
    - Structurally valid
    - Allowed by system constraints
    - Safe to execute within the specified root directory

    Args:
        plan: List of action dictionaries generated by the planner.
              Each action must conform to the expected schema.
        root_dir: The root directory that the agent is allowed to operate within.

    Returns:
        A validated list of actions safe for execution.

    Raises:
        ValueError: If the plan exceeds limits or contains invalid actions.
    """

    if len(plan) > MAX_ACTIONS:
        raise ValueError("Plan too large")

    validated_actions = []

    for action in plan:
        validated_action = validate_action(action, root_dir)
        if validated_action is not None:
            validated_actions.append(validated_action)

    return validated_actions


def validate_action(action: Dict, root_dir: str) -> Dict:
    """
    Validates a single action from the execution plan.

    Ensures the action:
    - Has required fields
    - Uses a supported action type
    - Passes action-specific validation rules

    Args:
        action: A dictionary representing a single planned operation.
        root_dir: The root directory constraint for safety checks.

    Returns:
        The validated action dictionary (unchanged if valid).
        None if action is invalid.
    """

    if "action" not in action:
        print("Discarding action: Missing action:" + action)
        return

    if action["action"] not in ALLOWED_ACTIONS:
        print("Discarding action: Illegal action: " + {action['action']})
        return

    if action["action"] == "move_item":
        move_error = validate_move(action, root_dir)
        if move_error:
            print(f"Discarding action: {move_error}")
            return None

    return action


def validate_move(action: Dict, root_dir: str) -> str:
    """
    Validates a move_item action to ensure filesystem safety.

    Checks:
    - Source path exists
    - Source is within allowed root directory
    - Destination folder is valid

    Args:
        action: Move action containing 'source' and 'destination_folder'
        root_dir: Allowed root directory boundary

    Returns:
        Empty string if move action is valid
        Corresponding error message if an issue is found.
    """

    src = os.path.abspath(action["source"])
    dst = os.path.abspath(action["destination_folder"])
    root_dir = os.path.abspath(root_dir)

    if not os.path.exists(src):
        return f"File does not exist: {src}"

    if os.path.commonpath([src, root_dir]) != root_dir:
        return f"File outside allowed directory: {src}"

    if not isinstance(dst, str) or len(dst) == 0:
        return f"Invalid destination folder {dst}"
    
    return ""