"""
Generates filesystem organization plans using an LLM.

This module is responsible for:
- Loading the planner prompt template
- Formatting filesystem information for the model
- Constructing the final prompt
- Requesting a structured execution plan from the LLM

The generated plan is later validated before execution.
"""

import json
from typing import List
from openai import OpenAI
from string import Template

client = OpenAI()


def load_prompt() -> str:
    """
    Loads the planner prompt template from disk.

    Returns:
        Raw prompt template contents.
    """
    with open("prompt.txt", "r", encoding="utf-8") as f:
        return f.read()


def format_files(files: List[str]) -> str:
    """
    Converts file list into a readable string for the LLM.
    """
    return "\n".join(files)


def generate_plan(goal: str, files: List[str], root_dir: str):
    """
    Generates a filesystem organization plan using the LLM.

    The prompt is constructed from:
    - The target root directory
    - The current filesystem contents
    - The user's organization goal

    Args:
        goal: User-specified organization objective.
        files: List of files and folders detected in the root directory.
        root_dir: Directory being organized.

    Returns:
        Parsed JSON execution plan generated by the model.

    Raises:
        json.JSONDecodeError:
            If the model response is not valid JSON.
    """
    prompt_template = load_prompt()

    formatted_files = format_files(files)

    prompt = Template(prompt_template).substitute(
        root_dir=root_dir,
        files=formatted_files,
        goal=goal
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0
    )

    content = response.choices[0].message.content
    return json.loads(content)